version: '2'
services:
  researchime-server:
    build:
      context: .
    ports:
      - 9000:9000
      - 9001:9001
    links:
      - researchime-db
    environment:
      - DB_USERNAME=languagelogger
      - DB_PASSWORD=G8BCjNk
      - APPLICATION_SECRET=researchime
      - DB_URL=jdbc:mysql://researchime-db/languageloggerdb?characterEncoding=UTF8&connectionCollation=utf8mb4_general_ci&verifyServerCertificate=false&useSSL=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  researchime-db:
    image: mysql:5.7
    ports:
      - 3306:3306
    command: ['mysqld', '--character-set-server=utf8mb4']
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: G8BCjNk
      MYSQL_DATABASE: languageloggerdb